env:
  TERM: xterm-256color

# Spread additional padding evenly around the terminal content.
window:
  padding:
    x: 10
    y: 10

custom_cursor_colors: true

colors:
  primary:
    background: '0x191919'
    foreground: '0xeaeaea'

cursor:
  # Block Underline or Beam
  style: Block

font:
  normal:
    family: JetBrains Mono
  # Font size
  size: 12
