alias l='ls -CF'
alias ls='ls -F'
alias ll='ls -lh'
alias la='ls -a'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias startsql='sudo service postgresql start'
alias cd..='cd ..'
alias wishlist='bash ~/bin/wishlist.sh' 
